let 🇦 = 1 /* regional indicator A */
let 🇧 = 1 /* regional indicator B */
let 🇨 = 1 /* regional indicator C */
let 🇩 = 1 /* regional indicator D */
let 🇪 = 1 /* regional indicator E */
let 🇫 = 1 /* regional indicator F */
let 🇬 = 1 /* regional indicator G */
let 🇭 = 1 /* regional indicator H */
let 🇮 = 1 /* regional indicator I */
let 🇯 = 1 /* regional indicator J */
let 🇰 = 1 /* regional indicator K */
let 🇱 = 1 /* regional indicator L */
let 🇲 = 1 /* regional indicator M */
let 🇳 = 1 /* regional indicator N */
let 🇴 = 1 /* regional indicator O */
let 🇵 = 1 /* regional indicator P */
let 🇶 = 1 /* regional indicator Q */
let 🇷 = 1 /* regional indicator R */
let 🇸 = 1 /* regional indicator S */
let 🇹 = 1 /* regional indicator T */
let 🇺 = 1 /* regional indicator U */
let 🇻 = 1 /* regional indicator V */
let 🇼 = 1 /* regional indicator W */
let 🇽 = 1 /* regional indicator X */
let 🇾 = 1 /* regional indicator Y */
let 🇿 = 1 /* regional indicator Z */
let 😀 = 1 /* grinning face */
let 😃 = 1 /* grinning face with big eyes */
let 😄 = 1 /* grinning face with smiling eyes */
let 😁 = 1 /* beaming face with smiling eyes */
let 😆 = 1 /* grinning squinting face */
let 😅 = 1 /* grinning face with sweat */
let 🤣 = 1 /* rolling on the floor laughing */
let 😂 = 1 /* face with tears of joy */
let 🙂 = 1 /* slightly smiling face */
let 🙃 = 1 /* upside-down face */
let 🫠 = 1 /* melting face */
let 😉 = 1 /* winking face */
let 😊 = 1 /* smiling face with smiling eyes */
let 😇 = 1 /* smiling face with halo */
let 🥰 = 1 /* smiling face with hearts */
let 😍 = 1 /* smiling face with heart-eyes */
let 🤩 = 1 /* star-struck */
let 😘 = 1 /* face blowing a kiss */
let 😗 = 1 /* kissing face */
let 😚 = 1 /* kissing face with closed eyes */
let 😙 = 1 /* kissing face with smiling eyes */
let 🥲 = 1 /* smiling face with tear */
let 😋 = 1 /* face savoring food */
let 😛 = 1 /* face with tongue */
let 😜 = 1 /* winking face with tongue */
let 🤪 = 1 /* zany face */
let 😝 = 1 /* squinting face with tongue */
let 🤑 = 1 /* money-mouth face */
let 🤗 = 1 /* smiling face with open hands */
let 🤭 = 1 /* face with hand over mouth */
let 🫢 = 1 /* face with open eyes and hand over mouth */
let 🫣 = 1 /* face with peeking eye */
let 🤫 = 1 /* shushing face */
let 🤔 = 1 /* thinking face */
let 🫡 = 1 /* saluting face */
let 🤐 = 1 /* zipper-mouth face */
let 🤨 = 1 /* face with raised eyebrow */
let 😐️ = 1 /* neutral face */
let 😑 = 1 /* expressionless face */
let 😶 = 1 /* face without mouth */
let 🫥 = 1 /* dotted line face */
let 😶‍🌫️ = 1 /* face in clouds */
let 😏 = 1 /* smirking face */
let 😒 = 1 /* unamused face */
let 🙄 = 1 /* face with rolling eyes */
let 😬 = 1 /* grimacing face */
let 😮‍💨 = 1 /* face exhaling */
let 🤥 = 1 /* lying face */
let 🫨 = 1 /* shaking face */
let 😌 = 1 /* relieved face */
let 😔 = 1 /* pensive face */
let 😪 = 1 /* sleepy face */
let 🤤 = 1 /* drooling face */
let 😴 = 1 /* sleeping face */
let 😷 = 1 /* face with medical mask */
let 🤒 = 1 /* face with thermometer */
let 🤕 = 1 /* face with head-bandage */
let 🤢 = 1 /* nauseated face */
let 🤮 = 1 /* face vomiting */
let 🤧 = 1 /* sneezing face */
let 🥵 = 1 /* hot face */
let 🥶 = 1 /* cold face */
let 🥴 = 1 /* woozy face */
let 😵 = 1 /* face with crossed-out eyes */
let 😵‍💫 = 1 /* face with spiral eyes */
let 🤯 = 1 /* exploding head */
let 🤠 = 1 /* cowboy hat face */
let 🥳 = 1 /* partying face */
let 🥸 = 1 /* disguised face */
let 😎 = 1 /* smiling face with sunglasses */
let 🤓 = 1 /* nerd face */
let 🧐 = 1 /* face with monocle */
let 😕 = 1 /* confused face */
let 🫤 = 1 /* face with diagonal mouth */
let 😟 = 1 /* worried face */
let 🙁 = 1 /* slightly frowning face */
let 😮 = 1 /* face with open mouth */
let 😯 = 1 /* hushed face */
let 😲 = 1 /* astonished face */
let 😳 = 1 /* flushed face */
let 🥺 = 1 /* pleading face */
let 🥹 = 1 /* face holding back tears */
let 😦 = 1 /* frowning face with open mouth */
let 😧 = 1 /* anguished face */
let 😨 = 1 /* fearful face */
let 😰 = 1 /* anxious face with sweat */
let 😥 = 1 /* sad but relieved face */
let 😢 = 1 /* crying face */
let 😭 = 1 /* loudly crying face */
let 😱 = 1 /* face screaming in fear */
let 😖 = 1 /* confounded face */
let 😣 = 1 /* persevering face */
let 😞 = 1 /* disappointed face */
let 😓 = 1 /* downcast face with sweat */
let 😩 = 1 /* weary face */
let 😫 = 1 /* tired face */
let 🥱 = 1 /* yawning face */
let 😤 = 1 /* face with steam from nose */
let 😡 = 1 /* enraged face */
let 😠 = 1 /* angry face */
let 🤬 = 1 /* face with symbols on mouth */
let 😈 = 1 /* smiling face with horns */
let 👿 = 1 /* angry face with horns */
let 💀 = 1 /* skull */
let 💩 = 1 /* pile of poo */
let 🤡 = 1 /* clown face */
let 👹 = 1 /* ogre */
let 👺 = 1 /* goblin */
let 👻 = 1 /* ghost */
let 👽️ = 1 /* alien */
let 👾 = 1 /* alien monster */
let 🤖 = 1 /* robot */
let 😺 = 1 /* grinning cat */
let 😸 = 1 /* grinning cat with smiling eyes */
let 😹 = 1 /* cat with tears of joy */
let 😻 = 1 /* smiling cat with heart-eyes */
let 😼 = 1 /* cat with wry smile */
let 😽 = 1 /* kissing cat */
let 🙀 = 1 /* weary cat */
let 😿 = 1 /* crying cat */
let 😾 = 1 /* pouting cat */
let 🙈 = 1 /* see-no-evil monkey */
let 🙉 = 1 /* hear-no-evil monkey */
let 🙊 = 1 /* speak-no-evil monkey */
let 💌 = 1 /* love letter */
let 💘 = 1 /* heart with arrow */
let 💝 = 1 /* heart with ribbon */
let 💖 = 1 /* sparkling heart */
let 💗 = 1 /* growing heart */
let 💓 = 1 /* beating heart */
let 💞 = 1 /* revolving hearts */
let 💕 = 1 /* two hearts */
let 💟 = 1 /* heart decoration */
let 💔 = 1 /* broken heart */
let 🩷 = 1 /* pink heart */
let 🧡 = 1 /* orange heart */
let 💛 = 1 /* yellow heart */
let 💚 = 1 /* green heart */
let 💙 = 1 /* blue heart */
let 🩵 = 1 /* light blue heart */
let 💜 = 1 /* purple heart */
let 🤎 = 1 /* brown heart */
let 🖤 = 1 /* black heart */
let 🩶 = 1 /* grey heart */
let 🤍 = 1 /* white heart */
let 💋 = 1 /* kiss mark */
let 💯 = 1 /* hundred points */
let 💢 = 1 /* anger symbol */
let 💥 = 1 /* collision */
let 💫 = 1 /* dizzy */
let 💦 = 1 /* sweat droplets */
let 💨 = 1 /* dashing away */
let 🕳️ = 1 /* hole */
let 💬 = 1 /* speech balloon */
let 👁️‍🗨️ = 1 /* eye in speech bubble */
let 🗨️ = 1 /* left speech bubble */
let 🗯️ = 1 /* right anger bubble */
let 💭 = 1 /* thought balloon */
let 💤 = 1 /* ZZZ */
let 👋 = 1 /* waving hand */
let 🤚 = 1 /* raised back of hand */
let 🖐️ = 1 /* hand with fingers splayed */
let 🖖 = 1 /* vulcan salute */
let 🫱 = 1 /* rightwards hand */
let 🫲 = 1 /* leftwards hand */
let 🫳 = 1 /* palm down hand */
let 🫴 = 1 /* palm up hand */
let 🫷 = 1 /* leftwards pushing hand */
let 🫸 = 1 /* rightwards pushing hand */
let 👌 = 1 /* OK hand */
let 🤌 = 1 /* pinched fingers */
let 🤏 = 1 /* pinching hand */
let 🤞 = 1 /* crossed fingers */
let 🫰 = 1 /* hand with index finger and thumb crossed */
let 🤟 = 1 /* love-you gesture */
let 🤘 = 1 /* sign of the horns */
let 🤙 = 1 /* call me hand */
let 👈️ = 1 /* backhand index pointing left */
let 👉️ = 1 /* backhand index pointing right */
let 👆️ = 1 /* backhand index pointing up */
let 🖕 = 1 /* middle finger */
let 👇️ = 1 /* backhand index pointing down */
let 🫵 = 1 /* index pointing at the viewer */
let 👍️ = 1 /* thumbs up */
let 👎️ = 1 /* thumbs down */
let 👊 = 1 /* oncoming fist */
let 🤛 = 1 /* left-facing fist */
let 🤜 = 1 /* right-facing fist */
let 👏 = 1 /* clapping hands */
let 🙌 = 1 /* raising hands */
let 🫶 = 1 /* heart hands */
let 👐 = 1 /* open hands */
let 🤲 = 1 /* palms up together */
let 🤝 = 1 /* handshake */
let 🙏 = 1 /* folded hands */
let 💅 = 1 /* nail polish */
let 🤳 = 1 /* selfie */
let 💪 = 1 /* flexed biceps */
let 🦾 = 1 /* mechanical arm */
let 🦿 = 1 /* mechanical leg */
let 🦵 = 1 /* leg */
let 🦶 = 1 /* foot */
let 👂️ = 1 /* ear */
let 🦻 = 1 /* ear with hearing aid */
let 👃 = 1 /* nose */
let 🧠 = 1 /* brain */
let 🫀 = 1 /* anatomical heart */
let 🫁 = 1 /* lungs */
let 🦷 = 1 /* tooth */
let 🦴 = 1 /* bone */
let 👀 = 1 /* eyes */
let 👁️ = 1 /* eye */
let 👅 = 1 /* tongue */
let 👄 = 1 /* mouth */
let 🫦 = 1 /* biting lip */
let 👶 = 1 /* baby */
let 🧒 = 1 /* child */
let 👦 = 1 /* boy */
let 👧 = 1 /* girl */
let 🧑 = 1 /* person */
let 👱 = 1 /* person: blond hair */
let 👨 = 1 /* man */
let 🧔 = 1 /* person: beard */
let 👨‍🦰 = 1 /* man: red hair */
let 👨‍🦱 = 1 /* man: curly hair */
let 👨‍🦳 = 1 /* man: white hair */
let 👨‍🦲 = 1 /* man: bald */
let 👩 = 1 /* woman */
let 👩‍🦰 = 1 /* woman: red hair */
let 🧑‍🦰 = 1 /* person: red hair */
let 👩‍🦱 = 1 /* woman: curly hair */
let 🧑‍🦱 = 1 /* person: curly hair */
let 👩‍🦳 = 1 /* woman: white hair */
let 🧑‍🦳 = 1 /* person: white hair */
let 👩‍🦲 = 1 /* woman: bald */
let 🧑‍🦲 = 1 /* person: bald */
let 🧓 = 1 /* older person */
let 👴 = 1 /* old man */
let 👵 = 1 /* old woman */
let 🙍 = 1 /* person frowning */
let 🙎 = 1 /* person pouting */
let 🙅 = 1 /* person gesturing NO */
let 🙆 = 1 /* person gesturing OK */
let 💁 = 1 /* person tipping hand */
let 🙋 = 1 /* person raising hand */
let 🧏 = 1 /* deaf person */
let 🙇 = 1 /* person bowing */
let 🤦 = 1 /* person facepalming */
let 🤷 = 1 /* person shrugging */
let 🧑‍🎓 = 1 /* student */
let 👨‍🎓 = 1 /* man student */
let 👩‍🎓 = 1 /* woman student */
let 🧑‍🏫 = 1 /* teacher */
let 👨‍🏫 = 1 /* man teacher */
let 👩‍🏫 = 1 /* woman teacher */
let 🧑‍🌾 = 1 /* farmer */
let 👨‍🌾 = 1 /* man farmer */
let 👩‍🌾 = 1 /* woman farmer */
let 🧑‍🍳 = 1 /* cook */
let 👨‍🍳 = 1 /* man cook */
let 👩‍🍳 = 1 /* woman cook */
let 🧑‍🔧 = 1 /* mechanic */
let 👨‍🔧 = 1 /* man mechanic */
let 👩‍🔧 = 1 /* woman mechanic */
let 🧑‍🏭 = 1 /* factory worker */
let 👨‍🏭 = 1 /* man factory worker */
let 👩‍🏭 = 1 /* woman factory worker */
let 🧑‍💼 = 1 /* office worker */
let 👨‍💼 = 1 /* man office worker */
let 👩‍💼 = 1 /* woman office worker */
let 🧑‍🔬 = 1 /* scientist */
let 👨‍🔬 = 1 /* man scientist */
let 👩‍🔬 = 1 /* woman scientist */
let 🧑‍💻 = 1 /* technologist */
let 👨‍💻 = 1 /* man technologist */
let 👩‍💻 = 1 /* woman technologist */
let 🧑‍🎤 = 1 /* singer */
let 👨‍🎤 = 1 /* man singer */
let 👩‍🎤 = 1 /* woman singer */
let 🧑‍🎨 = 1 /* artist */
let 👨‍🎨 = 1 /* man artist */
let 👩‍🎨 = 1 /* woman artist */
let 🧑‍🚀 = 1 /* astronaut */
let 👨‍🚀 = 1 /* man astronaut */
let 👩‍🚀 = 1 /* woman astronaut */
let 🧑‍🚒 = 1 /* firefighter */
let 👨‍🚒 = 1 /* man firefighter */
let 👩‍🚒 = 1 /* woman firefighter */
let 👮 = 1 /* police officer */
let 🕵️ = 1 /* detective */
let 💂 = 1 /* guard */
let 🥷 = 1 /* ninja */
let 👷 = 1 /* construction worker */
let 🫅 = 1 /* person with crown */
let 🤴 = 1 /* prince */
let 👸 = 1 /* princess */
let 👳 = 1 /* person wearing turban */
let 👲 = 1 /* person with skullcap */
let 🧕 = 1 /* woman with headscarf */
let 🤵 = 1 /* person in tuxedo */
let 👰 = 1 /* person with veil */
let 🤰 = 1 /* pregnant woman */
let 🫃 = 1 /* pregnant man */
let 🫄 = 1 /* pregnant person */
let 🤱 = 1 /* breast-feeding */
let 👩‍🍼 = 1 /* woman feeding baby */
let 👨‍🍼 = 1 /* man feeding baby */
let 🧑‍🍼 = 1 /* person feeding baby */
let 👼 = 1 /* baby angel */
let 🎅 = 1 /* Santa Claus */
let 🤶 = 1 /* Mrs. Claus */
let 🧑‍🎄 = 1 /* mx claus */
let 🦸 = 1 /* superhero */
let 🦹 = 1 /* supervillain */
let 🧙 = 1 /* mage */
let 🧚 = 1 /* fairy */
let 🧛 = 1 /* vampire */
let 🧜 = 1 /* merperson */
let 🧝 = 1 /* elf */
let 🧞 = 1 /* genie */
let 🧟 = 1 /* zombie */
let 🧌 = 1 /* troll */
let 💆 = 1 /* person getting massage */
let 💇 = 1 /* person getting haircut */
let 🚶 = 1 /* person walking */
let 🧍 = 1 /* person standing */
let 🧎 = 1 /* person kneeling */
let 🧑‍🦯 = 1 /* person with white cane */
let 👨‍🦯 = 1 /* man with white cane */
let 👩‍🦯 = 1 /* woman with white cane */
let 🧑‍🦼 = 1 /* person in motorized wheelchair */
let 👨‍🦼 = 1 /* man in motorized wheelchair */
let 👩‍🦼 = 1 /* woman in motorized wheelchair */
let 🧑‍🦽 = 1 /* person in manual wheelchair */
let 👨‍🦽 = 1 /* man in manual wheelchair */
let 👩‍🦽 = 1 /* woman in manual wheelchair */
let 🏃 = 1 /* person running */
let 💃 = 1 /* woman dancing */
let 🕺 = 1 /* man dancing */
let 🕴️ = 1 /* person in suit levitating */
let 👯 = 1 /* people with bunny ears */
let 🧖 = 1 /* person in steamy room */
let 🧗 = 1 /* person climbing */
let 🤺 = 1 /* person fencing */
let 🏇 = 1 /* horse racing */
let 🏂️ = 1 /* snowboarder */
let 🏌️ = 1 /* person golfing */
let 🏄️ = 1 /* person surfing */
let 🚣 = 1 /* person rowing boat */
let 🏊️ = 1 /* person swimming */
let 🏋️ = 1 /* person lifting weights */
let 🚴 = 1 /* person biking */
let 🚵 = 1 /* person mountain biking */
let 🤸 = 1 /* person cartwheeling */
let 🤼 = 1 /* people wrestling */
let 🤽 = 1 /* person playing water polo */
let 🤾 = 1 /* person playing handball */
let 🤹 = 1 /* person juggling */
let 🧘 = 1 /* person in lotus position */
let 🛀 = 1 /* person taking bath */
let 🛌 = 1 /* person in bed */
let 🧑‍🤝‍🧑 = 1 /* people holding hands */
let 👭 = 1 /* women holding hands */
let 👫 = 1 /* woman and man holding hands */
let 👬 = 1 /* men holding hands */
let 💏 = 1 /* kiss */
let 💑 = 1 /* couple with heart */
let 👨‍👩‍👦 = 1 /* family: man, woman, boy */
let 👨‍👩‍👧 = 1 /* family: man, woman, girl */
let 👨‍👩‍👧‍👦 = 1 /* family: man, woman, girl, boy */
let 👨‍👩‍👦‍👦 = 1 /* family: man, woman, boy, boy */
let 👨‍👩‍👧‍👧 = 1 /* family: man, woman, girl, girl */
let 👨‍👨‍👦 = 1 /* family: man, man, boy */
let 👨‍👨‍👧 = 1 /* family: man, man, girl */
let 👨‍👨‍👧‍👦 = 1 /* family: man, man, girl, boy */
let 👨‍👨‍👦‍👦 = 1 /* family: man, man, boy, boy */
let 👨‍👨‍👧‍👧 = 1 /* family: man, man, girl, girl */
let 👩‍👩‍👦 = 1 /* family: woman, woman, boy */
let 👩‍👩‍👧 = 1 /* family: woman, woman, girl */
let 👩‍👩‍👧‍👦 = 1 /* family: woman, woman, girl, boy */
let 👩‍👩‍👦‍👦 = 1 /* family: woman, woman, boy, boy */
let 👩‍👩‍👧‍👧 = 1 /* family: woman, woman, girl, girl */
let 👨‍👦 = 1 /* family: man, boy */
let 👨‍👦‍👦 = 1 /* family: man, boy, boy */
let 👨‍👧 = 1 /* family: man, girl */
let 👨‍👧‍👦 = 1 /* family: man, girl, boy */
let 👨‍👧‍👧 = 1 /* family: man, girl, girl */
let 👩‍👦 = 1 /* family: woman, boy */
let 👩‍👦‍👦 = 1 /* family: woman, boy, boy */
let 👩‍👧 = 1 /* family: woman, girl */
let 👩‍👧‍👦 = 1 /* family: woman, girl, boy */
let 👩‍👧‍👧 = 1 /* family: woman, girl, girl */
let 🗣️ = 1 /* speaking head */
let 👤 = 1 /* bust in silhouette */
let 👥 = 1 /* busts in silhouette */
let 🫂 = 1 /* people hugging */
let 👪️ = 1 /* family */
let 🧑‍🧑‍🧒 = 1 /* family: adult, adult, child */
let 🧑‍🧑‍🧒‍🧒 = 1 /* family: adult, adult, child, child */
let 🧑‍🧒 = 1 /* family: adult, child */
let 🧑‍🧒‍🧒 = 1 /* family: adult, child, child */
let 👣 = 1 /* footprints */
let 🏻 = 1 /* light skin tone */
let 🏼 = 1 /* medium-light skin tone */
let 🏽 = 1 /* medium skin tone */
let 🏾 = 1 /* medium-dark skin tone */
let 🏿 = 1 /* dark skin tone */
let 🦰 = 1 /* red hair */
let 🦱 = 1 /* curly hair */
let 🦳 = 1 /* white hair */
let 🦲 = 1 /* bald */
let 🐵 = 1 /* monkey face */
let 🐒 = 1 /* monkey */
let 🦍 = 1 /* gorilla */
let 🦧 = 1 /* orangutan */
let 🐶 = 1 /* dog face */
let 🐕️ = 1 /* dog */
let 🦮 = 1 /* guide dog */
let 🐕‍🦺 = 1 /* service dog */
let 🐩 = 1 /* poodle */
let 🐺 = 1 /* wolf */
let 🦊 = 1 /* fox */
let 🦝 = 1 /* raccoon */
let 🐱 = 1 /* cat face */
let 🐈️ = 1 /* cat */
let 🦁 = 1 /* lion */
let 🐯 = 1 /* tiger face */
let 🐅 = 1 /* tiger */
let 🐆 = 1 /* leopard */
let 🐴 = 1 /* horse face */
let 🫎 = 1 /* moose */
let 🫏 = 1 /* donkey */
let 🐎 = 1 /* horse */
let 🦄 = 1 /* unicorn */
let 🦓 = 1 /* zebra */
let 🦌 = 1 /* deer */
let 🦬 = 1 /* bison */
let 🐮 = 1 /* cow face */
let 🐂 = 1 /* ox */
let 🐃 = 1 /* water buffalo */
let 🐄 = 1 /* cow */
let 🐷 = 1 /* pig face */
let 🐖 = 1 /* pig */
let 🐗 = 1 /* boar */
let 🐽 = 1 /* pig nose */
let 🐏 = 1 /* ram */
let 🐑 = 1 /* ewe */
let 🐐 = 1 /* goat */
let 🐪 = 1 /* camel */
let 🐫 = 1 /* two-hump camel */
let 🦙 = 1 /* llama */
let 🦒 = 1 /* giraffe */
let 🐘 = 1 /* elephant */
let 🦣 = 1 /* mammoth */
let 🦏 = 1 /* rhinoceros */
let 🦛 = 1 /* hippopotamus */
let 🐭 = 1 /* mouse face */
let 🐁 = 1 /* mouse */
let 🐀 = 1 /* rat */
let 🐹 = 1 /* hamster */
let 🐰 = 1 /* rabbit face */
let 🐇 = 1 /* rabbit */
let 🐿️ = 1 /* chipmunk */
let 🦫 = 1 /* beaver */
let 🦔 = 1 /* hedgehog */
let 🦇 = 1 /* bat */
let 🐻 = 1 /* bear */
let 🐨 = 1 /* koala */
let 🐼 = 1 /* panda */
let 🦥 = 1 /* sloth */
let 🦦 = 1 /* otter */
let 🦨 = 1 /* skunk */
let 🦘 = 1 /* kangaroo */
let 🦡 = 1 /* badger */
let 🐾 = 1 /* paw prints */
let 🦃 = 1 /* turkey */
let 🐔 = 1 /* chicken */
let 🐓 = 1 /* rooster */
let 🐣 = 1 /* hatching chick */
let 🐤 = 1 /* baby chick */
let 🐥 = 1 /* front-facing baby chick */
let 🐦️ = 1 /* bird */
let 🐧 = 1 /* penguin */
let 🕊️ = 1 /* dove */
let 🦅 = 1 /* eagle */
let 🦆 = 1 /* duck */
let 🦢 = 1 /* swan */
let 🦉 = 1 /* owl */
let 🦤 = 1 /* dodo */
let 🪶 = 1 /* feather */
let 🦩 = 1 /* flamingo */
let 🦚 = 1 /* peacock */
let 🦜 = 1 /* parrot */
let 🪽 = 1 /* wing */
let 🪿 = 1 /* goose */
let 🐦‍🔥 = 1 /* phoenix */
let 🐸 = 1 /* frog */
let 🐊 = 1 /* crocodile */
let 🐢 = 1 /* turtle */
let 🦎 = 1 /* lizard */
let 🐍 = 1 /* snake */
let 🐲 = 1 /* dragon face */
let 🐉 = 1 /* dragon */
let 🦕 = 1 /* sauropod */
let 🦖 = 1 /* T-Rex */
let 🐳 = 1 /* spouting whale */
let 🐋 = 1 /* whale */
let 🐬 = 1 /* dolphin */
let 🦭 = 1 /* seal */
let 🐟️ = 1 /* fish */
let 🐠 = 1 /* tropical fish */
let 🐡 = 1 /* blowfish */
let 🦈 = 1 /* shark */
let 🐙 = 1 /* octopus */
let 🐚 = 1 /* spiral shell */
let 🪸 = 1 /* coral */
let 🪼 = 1 /* jellyfish */
let 🐌 = 1 /* snail */
let 🦋 = 1 /* butterfly */
let 🐛 = 1 /* bug */
let 🐜 = 1 /* ant */
let 🐝 = 1 /* honeybee */
let 🪲 = 1 /* beetle */
let 🐞 = 1 /* lady beetle */
let 🦗 = 1 /* cricket */
let 🪳 = 1 /* cockroach */
let 🕷️ = 1 /* spider */
let 🕸️ = 1 /* spider web */
let 🦂 = 1 /* scorpion */
let 🦟 = 1 /* mosquito */
let 🪰 = 1 /* fly */
let 🪱 = 1 /* worm */
let 🦠 = 1 /* microbe */
let 💐 = 1 /* bouquet */
let 🌸 = 1 /* cherry blossom */
let 💮 = 1 /* white flower */
let 🪷 = 1 /* lotus */
let 🏵️ = 1 /* rosette */
let 🌹 = 1 /* rose */
let 🥀 = 1 /* wilted flower */
let 🌺 = 1 /* hibiscus */
let 🌻 = 1 /* sunflower */
let 🌼 = 1 /* blossom */
let 🌷 = 1 /* tulip */
let 🪻 = 1 /* hyacinth */
let 🌱 = 1 /* seedling */
let 🪴 = 1 /* potted plant */
let 🌲 = 1 /* evergreen tree */
let 🌳 = 1 /* deciduous tree */
let 🌴 = 1 /* palm tree */
let 🌵 = 1 /* cactus */
let 🌾 = 1 /* sheaf of rice */
let 🌿 = 1 /* herb */
let 🍀 = 1 /* four leaf clover */
let 🍁 = 1 /* maple leaf */
let 🍂 = 1 /* fallen leaf */
let 🍃 = 1 /* leaf fluttering in wind */
let 🪹 = 1 /* empty nest */
let 🪺 = 1 /* nest with eggs */
let 🍄 = 1 /* mushroom */
let 🍇 = 1 /* grapes */
let 🍈 = 1 /* melon */
let 🍉 = 1 /* watermelon */
let 🍊 = 1 /* tangerine */
let 🍋 = 1 /* lemon */
let 🍋‍🟩 = 1 /* lime */
let 🍌 = 1 /* banana */
let 🍍 = 1 /* pineapple */
let 🥭 = 1 /* mango */
let 🍎 = 1 /* red apple */
let 🍏 = 1 /* green apple */
let 🍐 = 1 /* pear */
let 🍑 = 1 /* peach */
let 🍒 = 1 /* cherries */
let 🍓 = 1 /* strawberry */
let 🫐 = 1 /* blueberries */
let 🥝 = 1 /* kiwi fruit */
let 🍅 = 1 /* tomato */
let 🫒 = 1 /* olive */
let 🥥 = 1 /* coconut */
let 🥑 = 1 /* avocado */
let 🍆 = 1 /* eggplant */
let 🥔 = 1 /* potato */
let 🥕 = 1 /* carrot */
let 🌽 = 1 /* ear of corn */
let 🌶️ = 1 /* hot pepper */
let 🫑 = 1 /* bell pepper */
let 🥒 = 1 /* cucumber */
let 🥬 = 1 /* leafy green */
let 🥦 = 1 /* broccoli */
let 🧄 = 1 /* garlic */
let 🧅 = 1 /* onion */
let 🥜 = 1 /* peanuts */
let 🫘 = 1 /* beans */
let 🌰 = 1 /* chestnut */
let 🫚 = 1 /* ginger root */
let 🫛 = 1 /* pea pod */
let 🍄‍🟫 = 1 /* brown mushroom */
let 🍞 = 1 /* bread */
let 🥐 = 1 /* croissant */
let 🥖 = 1 /* baguette bread */
let 🫓 = 1 /* flatbread */
let 🥨 = 1 /* pretzel */
let 🥯 = 1 /* bagel */
let 🥞 = 1 /* pancakes */
let 🧇 = 1 /* waffle */
let 🧀 = 1 /* cheese wedge */
let 🍖 = 1 /* meat on bone */
let 🍗 = 1 /* poultry leg */
let 🥩 = 1 /* cut of meat */
let 🥓 = 1 /* bacon */
let 🍔 = 1 /* hamburger */
let 🍟 = 1 /* french fries */
let 🍕 = 1 /* pizza */
let 🌭 = 1 /* hot dog */
let 🥪 = 1 /* sandwich */
let 🌮 = 1 /* taco */
let 🌯 = 1 /* burrito */
let 🫔 = 1 /* tamale */
let 🥙 = 1 /* stuffed flatbread */
let 🧆 = 1 /* falafel */
let 🥚 = 1 /* egg */
let 🍳 = 1 /* cooking */
let 🥘 = 1 /* shallow pan of food */
let 🍲 = 1 /* pot of food */
let 🫕 = 1 /* fondue */
let 🥣 = 1 /* bowl with spoon */
let 🥗 = 1 /* green salad */
let 🍿 = 1 /* popcorn */
let 🧈 = 1 /* butter */
let 🧂 = 1 /* salt */
let 🥫 = 1 /* canned food */
let 🍱 = 1 /* bento box */
let 🍘 = 1 /* rice cracker */
let 🍙 = 1 /* rice ball */
let 🍚 = 1 /* cooked rice */
let 🍛 = 1 /* curry rice */
let 🍜 = 1 /* steaming bowl */
let 🍝 = 1 /* spaghetti */
let 🍠 = 1 /* roasted sweet potato */
let 🍢 = 1 /* oden */
let 🍣 = 1 /* sushi */
let 🍤 = 1 /* fried shrimp */
let 🍥 = 1 /* fish cake with swirl */
let 🥮 = 1 /* moon cake */
let 🍡 = 1 /* dango */
let 🥟 = 1 /* dumpling */
let 🥠 = 1 /* fortune cookie */
let 🥡 = 1 /* takeout box */
let 🦀 = 1 /* crab */
let 🦞 = 1 /* lobster */
let 🦐 = 1 /* shrimp */
let 🦑 = 1 /* squid */
let 🦪 = 1 /* oyster */
let 🍦 = 1 /* soft ice cream */
let 🍧 = 1 /* shaved ice */
let 🍨 = 1 /* ice cream */
let 🍩 = 1 /* doughnut */
let 🍪 = 1 /* cookie */
let 🎂 = 1 /* birthday cake */
let 🍰 = 1 /* shortcake */
let 🧁 = 1 /* cupcake */
let 🥧 = 1 /* pie */
let 🍫 = 1 /* chocolate bar */
let 🍬 = 1 /* candy */
let 🍭 = 1 /* lollipop */
let 🍮 = 1 /* custard */
let 🍯 = 1 /* honey pot */
let 🍼 = 1 /* baby bottle */
let 🥛 = 1 /* glass of milk */
let 🫖 = 1 /* teapot */
let 🍵 = 1 /* teacup without handle */
let 🍶 = 1 /* sake */
let 🍾 = 1 /* bottle with popping cork */
let 🍷 = 1 /* wine glass */
let 🍸️ = 1 /* cocktail glass */
let 🍹 = 1 /* tropical drink */
let 🍺 = 1 /* beer mug */
let 🍻 = 1 /* clinking beer mugs */
let 🥂 = 1 /* clinking glasses */
let 🥃 = 1 /* tumbler glass */
let 🫗 = 1 /* pouring liquid */
let 🥤 = 1 /* cup with straw */
let 🧋 = 1 /* bubble tea */
let 🧃 = 1 /* beverage box */
let 🧉 = 1 /* mate */
let 🧊 = 1 /* ice */
let 🥢 = 1 /* chopsticks */
let 🍽️ = 1 /* fork and knife with plate */
let 🍴 = 1 /* fork and knife */
let 🥄 = 1 /* spoon */
let 🔪 = 1 /* kitchen knife */
let 🫙 = 1 /* jar */
let 🏺 = 1 /* amphora */
let 🌍️ = 1 /* globe showing Europe-Africa */
let 🌎️ = 1 /* globe showing Americas */
let 🌏️ = 1 /* globe showing Asia-Australia */
let 🌐 = 1 /* globe with meridians */
let 🗺️ = 1 /* world map */
let 🗾 = 1 /* map of Japan */
let 🧭 = 1 /* compass */
let 🏔️ = 1 /* snow-capped mountain */
let 🌋 = 1 /* volcano */
let 🗻 = 1 /* mount fuji */
let 🏕️ = 1 /* camping */
let 🏖️ = 1 /* beach with umbrella */
let 🏜️ = 1 /* desert */
let 🏝️ = 1 /* desert island */
let 🏞️ = 1 /* national park */
let 🏟️ = 1 /* stadium */
let 🏛️ = 1 /* classical building */
let 🏗️ = 1 /* building construction */
let 🧱 = 1 /* brick */
let 🪨 = 1 /* rock */
let 🪵 = 1 /* wood */
let 🛖 = 1 /* hut */
let 🏘️ = 1 /* houses */
let 🏚️ = 1 /* derelict house */
let 🏠️ = 1 /* house */
let 🏡 = 1 /* house with garden */
let 🏢 = 1 /* office building */
let 🏣 = 1 /* Japanese post office */
let 🏤 = 1 /* post office */
let 🏥 = 1 /* hospital */
let 🏦 = 1 /* bank */
let 🏨 = 1 /* hotel */
let 🏩 = 1 /* love hotel */
let 🏪 = 1 /* convenience store */
let 🏫 = 1 /* school */
let 🏬 = 1 /* department store */
let 🏭️ = 1 /* factory */
let 🏯 = 1 /* Japanese castle */
let 🏰 = 1 /* castle */
let 💒 = 1 /* wedding */
let 🗼 = 1 /* Tokyo tower */
let 🗽 = 1 /* Statue of Liberty */
let 🕌 = 1 /* mosque */
let 🛕 = 1 /* hindu temple */
let 🕍 = 1 /* synagogue */
let 🕋 = 1 /* kaaba */
let 🌁 = 1 /* foggy */
let 🌃 = 1 /* night with stars */
let 🏙️ = 1 /* cityscape */
let 🌄 = 1 /* sunrise over mountains */
let 🌅 = 1 /* sunrise */
let 🌆 = 1 /* cityscape at dusk */
let 🌇 = 1 /* sunset */
let 🌉 = 1 /* bridge at night */
let 🎠 = 1 /* carousel horse */
let 🛝 = 1 /* playground slide */
let 🎡 = 1 /* ferris wheel */
let 🎢 = 1 /* roller coaster */
let 💈 = 1 /* barber pole */
let 🎪 = 1 /* circus tent */
let 🚂 = 1 /* locomotive */
let 🚃 = 1 /* railway car */
let 🚄 = 1 /* high-speed train */
let 🚅 = 1 /* bullet train */
let 🚆 = 1 /* train */
let 🚇️ = 1 /* metro */
let 🚈 = 1 /* light rail */
let 🚉 = 1 /* station */
let 🚊 = 1 /* tram */
let 🚝 = 1 /* monorail */
let 🚞 = 1 /* mountain railway */
let 🚋 = 1 /* tram car */
let 🚌 = 1 /* bus */
let 🚍️ = 1 /* oncoming bus */
let 🚎 = 1 /* trolleybus */
let 🚐 = 1 /* minibus */
let 🚑️ = 1 /* ambulance */
let 🚒 = 1 /* fire engine */
let 🚓 = 1 /* police car */
let 🚔️ = 1 /* oncoming police car */
let 🚕 = 1 /* taxi */
let 🚖 = 1 /* oncoming taxi */
let 🚗 = 1 /* automobile */
let 🚘️ = 1 /* oncoming automobile */
let 🚙 = 1 /* sport utility vehicle */
let 🛻 = 1 /* pickup truck */
let 🚚 = 1 /* delivery truck */
let 🚛 = 1 /* articulated lorry */
let 🚜 = 1 /* tractor */
let 🏎️ = 1 /* racing car */
let 🏍️ = 1 /* motorcycle */
let 🛵 = 1 /* motor scooter */
let 🦽 = 1 /* manual wheelchair */
let 🦼 = 1 /* motorized wheelchair */
let 🛺 = 1 /* auto rickshaw */
let 🚲️ = 1 /* bicycle */
let 🛴 = 1 /* kick scooter */
let 🛹 = 1 /* skateboard */
let 🛼 = 1 /* roller skate */
let 🚏 = 1 /* bus stop */
let 🛣️ = 1 /* motorway */
let 🛤️ = 1 /* railway track */
let 🛢️ = 1 /* oil drum */
let 🛞 = 1 /* wheel */
let 🚨 = 1 /* police car light */
let 🚥 = 1 /* horizontal traffic light */
let 🚦 = 1 /* vertical traffic light */
let 🛑 = 1 /* stop sign */
let 🚧 = 1 /* construction */
let 🛟 = 1 /* ring buoy */
let 🛶 = 1 /* canoe */
let 🚤 = 1 /* speedboat */
let 🛳️ = 1 /* passenger ship */
let 🛥️ = 1 /* motor boat */
let 🚢 = 1 /* ship */
let 🛩️ = 1 /* small airplane */
let 🛫 = 1 /* airplane departure */
let 🛬 = 1 /* airplane arrival */
let 🪂 = 1 /* parachute */
let 💺 = 1 /* seat */
let 🚁 = 1 /* helicopter */
let 🚟 = 1 /* suspension railway */
let 🚠 = 1 /* mountain cableway */
let 🚡 = 1 /* aerial tramway */
let 🛰️ = 1 /* satellite */
let 🚀 = 1 /* rocket */
let 🛸 = 1 /* flying saucer */
let 🛎️ = 1 /* bellhop bell */
let 🧳 = 1 /* luggage */
let 🕰️ = 1 /* mantelpiece clock */
let 🕛️ = 1 /* twelve o’clock */
let 🕧️ = 1 /* twelve-thirty */
let 🕐️ = 1 /* one o’clock */
let 🕜️ = 1 /* one-thirty */
let 🕑️ = 1 /* two o’clock */
let 🕝️ = 1 /* two-thirty */
let 🕒️ = 1 /* three o’clock */
let 🕞️ = 1 /* three-thirty */
let 🕓️ = 1 /* four o’clock */
let 🕟️ = 1 /* four-thirty */
let 🕔️ = 1 /* five o’clock */
let 🕠️ = 1 /* five-thirty */
let 🕕️ = 1 /* six o’clock */
let 🕡️ = 1 /* six-thirty */
let 🕖️ = 1 /* seven o’clock */
let 🕢️ = 1 /* seven-thirty */
let 🕗️ = 1 /* eight o’clock */
let 🕣️ = 1 /* eight-thirty */
let 🕘️ = 1 /* nine o’clock */
let 🕤️ = 1 /* nine-thirty */
let 🕙️ = 1 /* ten o’clock */
let 🕥️ = 1 /* ten-thirty */
let 🕚️ = 1 /* eleven o’clock */
let 🕦️ = 1 /* eleven-thirty */
let 🌑 = 1 /* new moon */
let 🌒 = 1 /* waxing crescent moon */
let 🌓 = 1 /* first quarter moon */
let 🌔 = 1 /* waxing gibbous moon */
let 🌕️ = 1 /* full moon */
let 🌖 = 1 /* waning gibbous moon */
let 🌗 = 1 /* last quarter moon */
let 🌘 = 1 /* waning crescent moon */
let 🌙 = 1 /* crescent moon */
let 🌚 = 1 /* new moon face */
let 🌛 = 1 /* first quarter moon face */
let 🌜️ = 1 /* last quarter moon face */
let 🌡️ = 1 /* thermometer */
let 🌝 = 1 /* full moon face */
let 🌞 = 1 /* sun with face */
let 🪐 = 1 /* ringed planet */
let 🌟 = 1 /* glowing star */
let 🌠 = 1 /* shooting star */
let 🌌 = 1 /* milky way */
let 🌤️ = 1 /* sun behind small cloud */
let 🌥️ = 1 /* sun behind large cloud */
let 🌦️ = 1 /* sun behind rain cloud */
let 🌧️ = 1 /* cloud with rain */
let 🌨️ = 1 /* cloud with snow */
let 🌩️ = 1 /* cloud with lightning */
let 🌪️ = 1 /* tornado */
let 🌫️ = 1 /* fog */
let 🌬️ = 1 /* wind face */
let 🌀 = 1 /* cyclone */
let 🌈 = 1 /* rainbow */
let 🌂 = 1 /* closed umbrella */
let 🔥 = 1 /* fire */
let 💧 = 1 /* droplet */
let 🌊 = 1 /* water wave */
let 🎃 = 1 /* jack-o-lantern */
let 🎄 = 1 /* Christmas tree */
let 🎆 = 1 /* fireworks */
let 🎇 = 1 /* sparkler */
let 🧨 = 1 /* firecracker */
let 🎈 = 1 /* balloon */
let 🎉 = 1 /* party popper */
let 🎊 = 1 /* confetti ball */
let 🎋 = 1 /* tanabata tree */
let 🎍 = 1 /* pine decoration */
let 🎎 = 1 /* Japanese dolls */
let 🎏 = 1 /* carp streamer */
let 🎐 = 1 /* wind chime */
let 🎑 = 1 /* moon viewing ceremony */
let 🧧 = 1 /* red envelope */
let 🎀 = 1 /* ribbon */
let 🎁 = 1 /* wrapped gift */
let 🎗️ = 1 /* reminder ribbon */
let 🎟️ = 1 /* admission tickets */
let 🎫 = 1 /* ticket */
let 🎖️ = 1 /* military medal */
let 🏆️ = 1 /* trophy */
let 🏅 = 1 /* sports medal */
let 🥇 = 1 /* 1st place medal */
let 🥈 = 1 /* 2nd place medal */
let 🥉 = 1 /* 3rd place medal */
let 🥎 = 1 /* softball */
let 🏀 = 1 /* basketball */
let 🏐 = 1 /* volleyball */
let 🏈 = 1 /* american football */
let 🏉 = 1 /* rugby football */
let 🎾 = 1 /* tennis */
let 🥏 = 1 /* flying disc */
let 🎳 = 1 /* bowling */
let 🏏 = 1 /* cricket game */
let 🏑 = 1 /* field hockey */
let 🏒 = 1 /* ice hockey */
let 🥍 = 1 /* lacrosse */
let 🏓 = 1 /* ping pong */
let 🏸 = 1 /* badminton */
let 🥊 = 1 /* boxing glove */
let 🥋 = 1 /* martial arts uniform */
let 🥅 = 1 /* goal net */
let 🎣 = 1 /* fishing pole */
let 🤿 = 1 /* diving mask */
let 🎽 = 1 /* running shirt */
let 🎿 = 1 /* skis */
let 🛷 = 1 /* sled */
let 🥌 = 1 /* curling stone */
let 🎯 = 1 /* bullseye */
let 🪀 = 1 /* yo-yo */
let 🪁 = 1 /* kite */
let 🔫 = 1 /* water pistol */
let 🎱 = 1 /* pool 8 ball */
let 🔮 = 1 /* crystal ball */
let 🪄 = 1 /* magic wand */
let 🎮️ = 1 /* video game */
let 🕹️ = 1 /* joystick */
let 🎰 = 1 /* slot machine */
let 🎲 = 1 /* game die */
let 🧩 = 1 /* puzzle piece */
let 🧸 = 1 /* teddy bear */
let 🪅 = 1 /* piñata */
let 🪩 = 1 /* mirror ball */
let 🪆 = 1 /* nesting dolls */
let 🃏 = 1 /* joker */
let 🀄️ = 1 /* mahjong red dragon */
let 🎴 = 1 /* flower playing cards */
let 🎭️ = 1 /* performing arts */
let 🖼️ = 1 /* framed picture */
let 🎨 = 1 /* artist palette */
let 🧵 = 1 /* thread */
let 🪡 = 1 /* sewing needle */
let 🧶 = 1 /* yarn */
let 🪢 = 1 /* knot */
let 👓️ = 1 /* glasses */
let 🕶️ = 1 /* sunglasses */
let 🥽 = 1 /* goggles */
let 🥼 = 1 /* lab coat */
let 🦺 = 1 /* safety vest */
let 👔 = 1 /* necktie */
let 👕 = 1 /* t-shirt */
let 👖 = 1 /* jeans */
let 🧣 = 1 /* scarf */
let 🧤 = 1 /* gloves */
let 🧥 = 1 /* coat */
let 🧦 = 1 /* socks */
let 👗 = 1 /* dress */
let 👘 = 1 /* kimono */
let 🥻 = 1 /* sari */
let 🩱 = 1 /* one-piece swimsuit */
let 🩲 = 1 /* briefs */
let 🩳 = 1 /* shorts */
let 👙 = 1 /* bikini */
let 👚 = 1 /* woman’s clothes */
let 🪭 = 1 /* folding hand fan */
let 👛 = 1 /* purse */
let 👜 = 1 /* handbag */
let 👝 = 1 /* clutch bag */
let 🛍️ = 1 /* shopping bags */
let 🎒 = 1 /* backpack */
let 🩴 = 1 /* thong sandal */
let 👞 = 1 /* man’s shoe */
let 👟 = 1 /* running shoe */
let 🥾 = 1 /* hiking boot */
let 🥿 = 1 /* flat shoe */
let 👠 = 1 /* high-heeled shoe */
let 👡 = 1 /* woman’s sandal */
let 🩰 = 1 /* ballet shoes */
let 👢 = 1 /* woman’s boot */
let 🪮 = 1 /* hair pick */
let 👑 = 1 /* crown */
let 👒 = 1 /* woman’s hat */
let 🎩 = 1 /* top hat */
let 🎓️ = 1 /* graduation cap */
let 🧢 = 1 /* billed cap */
let 🪖 = 1 /* military helmet */
let 📿 = 1 /* prayer beads */
let 💄 = 1 /* lipstick */
let 💍 = 1 /* ring */
let 💎 = 1 /* gem stone */
let 🔇 = 1 /* muted speaker */
let 🔈️ = 1 /* speaker low volume */
let 🔉 = 1 /* speaker medium volume */
let 🔊 = 1 /* speaker high volume */
let 📢 = 1 /* loudspeaker */
let 📣 = 1 /* megaphone */
let 📯 = 1 /* postal horn */
let 🔔 = 1 /* bell */
let 🔕 = 1 /* bell with slash */
let 🎼 = 1 /* musical score */
let 🎵 = 1 /* musical note */
let 🎶 = 1 /* musical notes */
let 🎙️ = 1 /* studio microphone */
let 🎚️ = 1 /* level slider */
let 🎛️ = 1 /* control knobs */
let 🎤 = 1 /* microphone */
let 🎧️ = 1 /* headphone */
let 📻️ = 1 /* radio */
let 🎷 = 1 /* saxophone */
let 🪗 = 1 /* accordion */
let 🎸 = 1 /* guitar */
let 🎹 = 1 /* musical keyboard */
let 🎺 = 1 /* trumpet */
let 🎻 = 1 /* violin */
let 🪕 = 1 /* banjo */
let 🥁 = 1 /* drum */
let 🪘 = 1 /* long drum */
let 🪇 = 1 /* maracas */
let 🪈 = 1 /* flute */
let 📱 = 1 /* mobile phone */
let 📲 = 1 /* mobile phone with arrow */
let 📞 = 1 /* telephone receiver */
let 📟️ = 1 /* pager */
let 📠 = 1 /* fax machine */
let 🔋 = 1 /* battery */
let 🪫 = 1 /* low battery */
let 🔌 = 1 /* electric plug */
let 💻️ = 1 /* laptop */
let 🖥️ = 1 /* desktop computer */
let 🖨️ = 1 /* printer */
let 🖱️ = 1 /* computer mouse */
let 🖲️ = 1 /* trackball */
let 💽 = 1 /* computer disk */
let 💾 = 1 /* floppy disk */
let 💿️ = 1 /* optical disk */
let 📀 = 1 /* dvd */
let 🧮 = 1 /* abacus */
let 🎥 = 1 /* movie camera */
let 🎞️ = 1 /* film frames */
let 📽️ = 1 /* film projector */
let 🎬️ = 1 /* clapper board */
let 📺️ = 1 /* television */
let 📷️ = 1 /* camera */
let 📸 = 1 /* camera with flash */
let 📹️ = 1 /* video camera */
let 📼 = 1 /* videocassette */
let 🔍️ = 1 /* magnifying glass tilted left */
let 🔎 = 1 /* magnifying glass tilted right */
let 🕯️ = 1 /* candle */
let 💡 = 1 /* light bulb */
let 🔦 = 1 /* flashlight */
let 🏮 = 1 /* red paper lantern */
let 🪔 = 1 /* diya lamp */
let 📔 = 1 /* notebook with decorative cover */
let 📕 = 1 /* closed book */
let 📖 = 1 /* open book */
let 📗 = 1 /* green book */
let 📘 = 1 /* blue book */
let 📙 = 1 /* orange book */
let 📚️ = 1 /* books */
let 📓 = 1 /* notebook */
let 📒 = 1 /* ledger */
let 📃 = 1 /* page with curl */
let 📜 = 1 /* scroll */
let 📄 = 1 /* page facing up */
let 📰 = 1 /* newspaper */
let 🗞️ = 1 /* rolled-up newspaper */
let 📑 = 1 /* bookmark tabs */
let 🔖 = 1 /* bookmark */
let 🏷️ = 1 /* label */
let 💰️ = 1 /* money bag */
let 🪙 = 1 /* coin */
let 💴 = 1 /* yen banknote */
let 💵 = 1 /* dollar banknote */
let 💶 = 1 /* euro banknote */
let 💷 = 1 /* pound banknote */
let 💸 = 1 /* money with wings */
let 💳️ = 1 /* credit card */
let 🧾 = 1 /* receipt */
let 💹 = 1 /* chart increasing with yen */
let 📧 = 1 /* e-mail */
let 📨 = 1 /* incoming envelope */
let 📩 = 1 /* envelope with arrow */
let 📤️ = 1 /* outbox tray */
let 📥️ = 1 /* inbox tray */
let 📦️ = 1 /* package */
let 📫️ = 1 /* closed mailbox with raised flag */
let 📪️ = 1 /* closed mailbox with lowered flag */
let 📬️ = 1 /* open mailbox with raised flag */
let 📭️ = 1 /* open mailbox with lowered flag */
let 📮 = 1 /* postbox */
let 🗳️ = 1 /* ballot box with ballot */
let 🖋️ = 1 /* fountain pen */
let 🖊️ = 1 /* pen */
let 🖌️ = 1 /* paintbrush */
let 🖍️ = 1 /* crayon */
let 📝 = 1 /* memo */
let 💼 = 1 /* briefcase */
let 📁 = 1 /* file folder */
let 📂 = 1 /* open file folder */
let 🗂️ = 1 /* card index dividers */
let 📅 = 1 /* calendar */
let 📆 = 1 /* tear-off calendar */
let 🗒️ = 1 /* spiral notepad */
let 🗓️ = 1 /* spiral calendar */
let 📇 = 1 /* card index */
let 📈 = 1 /* chart increasing */
let 📉 = 1 /* chart decreasing */
let 📊 = 1 /* bar chart */
let 📋️ = 1 /* clipboard */
let 📌 = 1 /* pushpin */
let 📍 = 1 /* round pushpin */
let 📎 = 1 /* paperclip */
let 🖇️ = 1 /* linked paperclips */
let 📏 = 1 /* straight ruler */
let 📐 = 1 /* triangular ruler */
let 🗃️ = 1 /* card file box */
let 🗄️ = 1 /* file cabinet */
let 🗑️ = 1 /* wastebasket */
let 🔒️ = 1 /* locked */
let 🔓️ = 1 /* unlocked */
let 🔏 = 1 /* locked with pen */
let 🔐 = 1 /* locked with key */
let 🔑 = 1 /* key */
let 🗝️ = 1 /* old key */
let 🔨 = 1 /* hammer */
let 🪓 = 1 /* axe */
let 🛠️ = 1 /* hammer and wrench */
let 🗡️ = 1 /* dagger */
let 💣️ = 1 /* bomb */
let 🪃 = 1 /* boomerang */
let 🏹 = 1 /* bow and arrow */
let 🛡️ = 1 /* shield */
let 🪚 = 1 /* carpentry saw */
let 🔧 = 1 /* wrench */
let 🪛 = 1 /* screwdriver */
let 🔩 = 1 /* nut and bolt */
let 🗜️ = 1 /* clamp */
let 🦯 = 1 /* white cane */
let 🔗 = 1 /* link */
let 🪝 = 1 /* hook */
let 🧰 = 1 /* toolbox */
let 🧲 = 1 /* magnet */
let 🪜 = 1 /* ladder */
let 🧪 = 1 /* test tube */
let 🧫 = 1 /* petri dish */
let 🧬 = 1 /* dna */
let 🔬 = 1 /* microscope */
let 🔭 = 1 /* telescope */
let 📡 = 1 /* satellite antenna */
let 💉 = 1 /* syringe */
let 🩸 = 1 /* drop of blood */
let 💊 = 1 /* pill */
let 🩹 = 1 /* adhesive bandage */
let 🩼 = 1 /* crutch */
let 🩺 = 1 /* stethoscope */
let 🩻 = 1 /* x-ray */
let 🚪 = 1 /* door */
let 🛗 = 1 /* elevator */
let 🪞 = 1 /* mirror */
let 🪟 = 1 /* window */
let 🛏️ = 1 /* bed */
let 🛋️ = 1 /* couch and lamp */
let 🪑 = 1 /* chair */
let 🚽 = 1 /* toilet */
let 🪠 = 1 /* plunger */
let 🚿 = 1 /* shower */
let 🛁 = 1 /* bathtub */
let 🪤 = 1 /* mouse trap */
let 🪒 = 1 /* razor */
let 🧴 = 1 /* lotion bottle */
let 🧷 = 1 /* safety pin */
let 🧹 = 1 /* broom */
let 🧺 = 1 /* basket */
let 🧻 = 1 /* roll of paper */
let 🪣 = 1 /* bucket */
let 🧼 = 1 /* soap */
let 🫧 = 1 /* bubbles */
let 🪥 = 1 /* toothbrush */
let 🧽 = 1 /* sponge */
let 🧯 = 1 /* fire extinguisher */
let 🛒 = 1 /* shopping cart */
let 🚬 = 1 /* cigarette */
let 🪦 = 1 /* headstone */
let 🧿 = 1 /* nazar amulet */
let 🪬 = 1 /* hamsa */
let 🗿 = 1 /* moai */
let 🪧 = 1 /* placard */
let 🪪 = 1 /* identification card */
let 🏧 = 1 /* ATM sign */
let 🚮 = 1 /* litter in bin sign */
let 🚰 = 1 /* potable water */
let 🚹️ = 1 /* men’s room */
let 🚺️ = 1 /* women’s room */
let 🚻 = 1 /* restroom */
let 🚼️ = 1 /* baby symbol */
let 🚾 = 1 /* water closet */
let 🛂 = 1 /* passport control */
let 🛃 = 1 /* customs */
let 🛄 = 1 /* baggage claim */
let 🛅 = 1 /* left luggage */
let 🚸 = 1 /* children crossing */
let 🚫 = 1 /* prohibited */
let 🚳 = 1 /* no bicycles */
let 🚭️ = 1 /* no smoking */
let 🚯 = 1 /* no littering */
let 🚱 = 1 /* non-potable water */
let 🚷 = 1 /* no pedestrians */
let 📵 = 1 /* no mobile phones */
let 🔞 = 1 /* no one under eighteen */
let 🔃 = 1 /* clockwise vertical arrows */
let 🔄 = 1 /* counterclockwise arrows button */
let 🔙 = 1 /* BACK arrow */
let 🔚 = 1 /* END arrow */
let 🔛 = 1 /* ON! arrow */
let 🔜 = 1 /* SOON arrow */
let 🔝 = 1 /* TOP arrow */
let 🛐 = 1 /* place of worship */
let 🕉️ = 1 /* om */
let 🕎 = 1 /* menorah */
let 🔯 = 1 /* dotted six-pointed star */
let 🪯 = 1 /* khanda */
let 🔀 = 1 /* shuffle tracks button */
let 🔁 = 1 /* repeat button */
let 🔂 = 1 /* repeat single button */
let 🔼 = 1 /* upwards button */
let 🔽 = 1 /* downwards button */
let 🎦 = 1 /* cinema */
let 🔅 = 1 /* dim button */
let 🔆 = 1 /* bright button */
let 📶 = 1 /* antenna bars */
let 🛜 = 1 /* wireless */
let 📳 = 1 /* vibration mode */
let 📴 = 1 /* mobile phone off */
let 🟰 = 1 /* heavy equals sign */
let 💱 = 1 /* currency exchange */
let 💲 = 1 /* heavy dollar sign */
let 🔱 = 1 /* trident emblem */
let 📛 = 1 /* name badge */
let 🔰 = 1 /* Japanese symbol for beginner */
let 〽️ = 1 /* part alternation mark */
let ™️ = 1 /* trade mark */
let 🔟 = 1 /* keycap: 10 */
let 🔠 = 1 /* input latin uppercase */
let 🔡 = 1 /* input latin lowercase */
let 🔢 = 1 /* input numbers */
let 🔣 = 1 /* input symbols */
let 🔤 = 1 /* input latin letters */
let 🅰️ = 1 /* A button (blood type) */
let 🆎 = 1 /* AB button (blood type) */
let 🅱️ = 1 /* B button (blood type) */
let 🆑 = 1 /* CL button */
let 🆒 = 1 /* COOL button */
let 🆓 = 1 /* FREE button */
let ℹ️ = 1 /* information */
let 🆔 = 1 /* ID button */
let Ⓜ️ = 1 /* circled M */
let 🆕 = 1 /* NEW button */
let 🆖 = 1 /* NG button */
let 🅾️ = 1 /* O button (blood type) */
let 🆗 = 1 /* OK button */
let 🅿️ = 1 /* P button */
let 🆘 = 1 /* SOS button */
let 🆙 = 1 /* UP! button */
let 🆚 = 1 /* VS button */
let 🈁 = 1 /* Japanese “here” button */
let 🈂️ = 1 /* Japanese “service charge” button */
let 🈷️ = 1 /* Japanese “monthly amount” button */
let 🈶 = 1 /* Japanese “not free of charge” button */
let 🈯️ = 1 /* Japanese “reserved” button */
let 🉐 = 1 /* Japanese “bargain” button */
let 🈹 = 1 /* Japanese “discount” button */
let 🈚️ = 1 /* Japanese “free of charge” button */
let 🈲 = 1 /* Japanese “prohibited” button */
let 🉑 = 1 /* Japanese “acceptable” button */
let 🈸 = 1 /* Japanese “application” button */
let 🈴 = 1 /* Japanese “passing grade” button */
let 🈳 = 1 /* Japanese “vacancy” button */
let ㊗️ = 1 /* Japanese “congratulations” button */
let ㊙️ = 1 /* Japanese “secret” button */
let 🈺 = 1 /* Japanese “open for business” button */
let 🈵 = 1 /* Japanese “no vacancy” button */
let 🔴 = 1 /* red circle */
let 🟠 = 1 /* orange circle */
let 🟡 = 1 /* yellow circle */
let 🟢 = 1 /* green circle */
let 🔵 = 1 /* blue circle */
let 🟣 = 1 /* purple circle */
let 🟤 = 1 /* brown circle */
let 🟥 = 1 /* red square */
let 🟧 = 1 /* orange square */
let 🟨 = 1 /* yellow square */
let 🟩 = 1 /* green square */
let 🟦 = 1 /* blue square */
let 🟪 = 1 /* purple square */
let 🟫 = 1 /* brown square */
let 🔶 = 1 /* large orange diamond */
let 🔷 = 1 /* large blue diamond */
let 🔸 = 1 /* small orange diamond */
let 🔹 = 1 /* small blue diamond */
let 🔺 = 1 /* red triangle pointed up */
let 🔻 = 1 /* red triangle pointed down */
let 💠 = 1 /* diamond with a dot */
let 🔘 = 1 /* radio button */
let 🔳 = 1 /* white square button */
let 🔲 = 1 /* black square button */
let 🏁 = 1 /* chequered flag */
let 🚩 = 1 /* triangular flag */
let 🎌 = 1 /* crossed flags */
let 🏴 = 1 /* black flag */
let 🏳️ = 1 /* white flag */
let 🏳️‍🌈 = 1 /* rainbow flag */
let 🇦🇨 = 1 /* flag: Ascension Island */
let 🇦🇩 = 1 /* flag: Andorra */
let 🇦🇪 = 1 /* flag: United Arab Emirates */
let 🇦🇫 = 1 /* flag: Afghanistan */
let 🇦🇬 = 1 /* flag: Antigua & Barbuda */
let 🇦🇮 = 1 /* flag: Anguilla */
let 🇦🇱 = 1 /* flag: Albania */
let 🇦🇲 = 1 /* flag: Armenia */
let 🇦🇴 = 1 /* flag: Angola */
let 🇦🇶 = 1 /* flag: Antarctica */
let 🇦🇷 = 1 /* flag: Argentina */
let 🇦🇸 = 1 /* flag: American Samoa */
let 🇦🇹 = 1 /* flag: Austria */
let 🇦🇺 = 1 /* flag: Australia */
let 🇦🇼 = 1 /* flag: Aruba */
let 🇦🇽 = 1 /* flag: Åland Islands */
let 🇦🇿 = 1 /* flag: Azerbaijan */
let 🇧🇦 = 1 /* flag: Bosnia & Herzegovina */
let 🇧🇧 = 1 /* flag: Barbados */
let 🇧🇩 = 1 /* flag: Bangladesh */
let 🇧🇪 = 1 /* flag: Belgium */
let 🇧🇫 = 1 /* flag: Burkina Faso */
let 🇧🇬 = 1 /* flag: Bulgaria */
let 🇧🇭 = 1 /* flag: Bahrain */
let 🇧🇮 = 1 /* flag: Burundi */
let 🇧🇯 = 1 /* flag: Benin */
let 🇧🇱 = 1 /* flag: St. Barthélemy */
let 🇧🇲 = 1 /* flag: Bermuda */
let 🇧🇳 = 1 /* flag: Brunei */
let 🇧🇴 = 1 /* flag: Bolivia */
let 🇧🇶 = 1 /* flag: Caribbean Netherlands */
let 🇧🇷 = 1 /* flag: Brazil */
let 🇧🇸 = 1 /* flag: Bahamas */
let 🇧🇹 = 1 /* flag: Bhutan */
let 🇧🇻 = 1 /* flag: Bouvet Island */
let 🇧🇼 = 1 /* flag: Botswana */
let 🇧🇾 = 1 /* flag: Belarus */
let 🇧🇿 = 1 /* flag: Belize */
let 🇨🇦 = 1 /* flag: Canada */
let 🇨🇨 = 1 /* flag: Cocos (Keeling) Islands */
let 🇨🇩 = 1 /* flag: Congo - Kinshasa */
let 🇨🇫 = 1 /* flag: Central African Republic */
let 🇨🇬 = 1 /* flag: Congo - Brazzaville */
let 🇨🇭 = 1 /* flag: Switzerland */
let 🇨🇮 = 1 /* flag: Côte d’Ivoire */
let 🇨🇰 = 1 /* flag: Cook Islands */
let 🇨🇱 = 1 /* flag: Chile */
let 🇨🇲 = 1 /* flag: Cameroon */
let 🇨🇳 = 1 /* flag: China */
let 🇨🇴 = 1 /* flag: Colombia */
let 🇨🇵 = 1 /* flag: Clipperton Island */
let 🇨🇷 = 1 /* flag: Costa Rica */
let 🇨🇺 = 1 /* flag: Cuba */
let 🇨🇻 = 1 /* flag: Cape Verde */
let 🇨🇼 = 1 /* flag: Curaçao */
let 🇨🇽 = 1 /* flag: Christmas Island */
let 🇨🇾 = 1 /* flag: Cyprus */
let 🇨🇿 = 1 /* flag: Czechia */
let 🇩🇪 = 1 /* flag: Germany */
let 🇩🇬 = 1 /* flag: Diego Garcia */
let 🇩🇯 = 1 /* flag: Djibouti */
let 🇩🇰 = 1 /* flag: Denmark */
let 🇩🇲 = 1 /* flag: Dominica */
let 🇩🇴 = 1 /* flag: Dominican Republic */
let 🇩🇿 = 1 /* flag: Algeria */
let 🇪🇦 = 1 /* flag: Ceuta & Melilla */
let 🇪🇨 = 1 /* flag: Ecuador */
let 🇪🇪 = 1 /* flag: Estonia */
let 🇪🇬 = 1 /* flag: Egypt */
let 🇪🇭 = 1 /* flag: Western Sahara */
let 🇪🇷 = 1 /* flag: Eritrea */
let 🇪🇸 = 1 /* flag: Spain */
let 🇪🇹 = 1 /* flag: Ethiopia */
let 🇪🇺 = 1 /* flag: European Union */
let 🇫🇮 = 1 /* flag: Finland */
let 🇫🇯 = 1 /* flag: Fiji */
let 🇫🇰 = 1 /* flag: Falkland Islands */
let 🇫🇲 = 1 /* flag: Micronesia */
let 🇫🇴 = 1 /* flag: Faroe Islands */
let 🇫🇷 = 1 /* flag: France */
let 🇬🇦 = 1 /* flag: Gabon */
let 🇬🇧 = 1 /* flag: United Kingdom */
let 🇬🇩 = 1 /* flag: Grenada */
let 🇬🇪 = 1 /* flag: Georgia */
let 🇬🇫 = 1 /* flag: French Guiana */
let 🇬🇬 = 1 /* flag: Guernsey */
let 🇬🇭 = 1 /* flag: Ghana */
let 🇬🇮 = 1 /* flag: Gibraltar */
let 🇬🇱 = 1 /* flag: Greenland */
let 🇬🇲 = 1 /* flag: Gambia */
let 🇬🇳 = 1 /* flag: Guinea */
let 🇬🇵 = 1 /* flag: Guadeloupe */
let 🇬🇶 = 1 /* flag: Equatorial Guinea */
let 🇬🇷 = 1 /* flag: Greece */
let 🇬🇸 = 1 /* flag: South Georgia & South Sandwich Islands */
let 🇬🇹 = 1 /* flag: Guatemala */
let 🇬🇺 = 1 /* flag: Guam */
let 🇬🇼 = 1 /* flag: Guinea-Bissau */
let 🇬🇾 = 1 /* flag: Guyana */
let 🇭🇰 = 1 /* flag: Hong Kong SAR China */
let 🇭🇲 = 1 /* flag: Heard & McDonald Islands */
let 🇭🇳 = 1 /* flag: Honduras */
let 🇭🇷 = 1 /* flag: Croatia */
let 🇭🇹 = 1 /* flag: Haiti */
let 🇭🇺 = 1 /* flag: Hungary */
let 🇮🇨 = 1 /* flag: Canary Islands */
let 🇮🇩 = 1 /* flag: Indonesia */
let 🇮🇪 = 1 /* flag: Ireland */
let 🇮🇱 = 1 /* flag: Israel */
let 🇮🇲 = 1 /* flag: Isle of Man */
let 🇮🇳 = 1 /* flag: India */
let 🇮🇴 = 1 /* flag: British Indian Ocean Territory */
let 🇮🇶 = 1 /* flag: Iraq */
let 🇮🇷 = 1 /* flag: Iran */
let 🇮🇸 = 1 /* flag: Iceland */
let 🇮🇹 = 1 /* flag: Italy */
let 🇯🇪 = 1 /* flag: Jersey */
let 🇯🇲 = 1 /* flag: Jamaica */
let 🇯🇴 = 1 /* flag: Jordan */
let 🇯🇵 = 1 /* flag: Japan */
let 🇰🇪 = 1 /* flag: Kenya */
let 🇰🇬 = 1 /* flag: Kyrgyzstan */
let 🇰🇭 = 1 /* flag: Cambodia */
let 🇰🇮 = 1 /* flag: Kiribati */
let 🇰🇲 = 1 /* flag: Comoros */
let 🇰🇳 = 1 /* flag: St. Kitts & Nevis */
let 🇰🇵 = 1 /* flag: North Korea */
let 🇰🇷 = 1 /* flag: South Korea */
let 🇰🇼 = 1 /* flag: Kuwait */
let 🇰🇾 = 1 /* flag: Cayman Islands */
let 🇰🇿 = 1 /* flag: Kazakhstan */
let 🇱🇦 = 1 /* flag: Laos */
let 🇱🇧 = 1 /* flag: Lebanon */
let 🇱🇨 = 1 /* flag: St. Lucia */
let 🇱🇮 = 1 /* flag: Liechtenstein */
let 🇱🇰 = 1 /* flag: Sri Lanka */
let 🇱🇷 = 1 /* flag: Liberia */
let 🇱🇸 = 1 /* flag: Lesotho */
let 🇱🇹 = 1 /* flag: Lithuania */
let 🇱🇺 = 1 /* flag: Luxembourg */
let 🇱🇻 = 1 /* flag: Latvia */
let 🇱🇾 = 1 /* flag: Libya */
let 🇲🇦 = 1 /* flag: Morocco */
let 🇲🇨 = 1 /* flag: Monaco */
let 🇲🇩 = 1 /* flag: Moldova */
let 🇲🇪 = 1 /* flag: Montenegro */
let 🇲🇫 = 1 /* flag: St. Martin */
let 🇲🇬 = 1 /* flag: Madagascar */
let 🇲🇭 = 1 /* flag: Marshall Islands */
let 🇲🇰 = 1 /* flag: North Macedonia */
let 🇲🇱 = 1 /* flag: Mali */
let 🇲🇲 = 1 /* flag: Myanmar (Burma) */
let 🇲🇳 = 1 /* flag: Mongolia */
let 🇲🇴 = 1 /* flag: Macao SAR China */
let 🇲🇵 = 1 /* flag: Northern Mariana Islands */
let 🇲🇶 = 1 /* flag: Martinique */
let 🇲🇷 = 1 /* flag: Mauritania */
let 🇲🇸 = 1 /* flag: Montserrat */
let 🇲🇹 = 1 /* flag: Malta */
let 🇲🇺 = 1 /* flag: Mauritius */
let 🇲🇻 = 1 /* flag: Maldives */
let 🇲🇼 = 1 /* flag: Malawi */
let 🇲🇽 = 1 /* flag: Mexico */
let 🇲🇾 = 1 /* flag: Malaysia */
let 🇲🇿 = 1 /* flag: Mozambique */
let 🇳🇦 = 1 /* flag: Namibia */
let 🇳🇨 = 1 /* flag: New Caledonia */
let 🇳🇪 = 1 /* flag: Niger */
let 🇳🇫 = 1 /* flag: Norfolk Island */
let 🇳🇬 = 1 /* flag: Nigeria */
let 🇳🇮 = 1 /* flag: Nicaragua */
let 🇳🇱 = 1 /* flag: Netherlands */
let 🇳🇴 = 1 /* flag: Norway */
let 🇳🇵 = 1 /* flag: Nepal */
let 🇳🇷 = 1 /* flag: Nauru */
let 🇳🇺 = 1 /* flag: Niue */
let 🇳🇿 = 1 /* flag: New Zealand */
let 🇴🇲 = 1 /* flag: Oman */
let 🇵🇦 = 1 /* flag: Panama */
let 🇵🇪 = 1 /* flag: Peru */
let 🇵🇫 = 1 /* flag: French Polynesia */
let 🇵🇬 = 1 /* flag: Papua New Guinea */
let 🇵🇭 = 1 /* flag: Philippines */
let 🇵🇰 = 1 /* flag: Pakistan */
let 🇵🇱 = 1 /* flag: Poland */
let 🇵🇲 = 1 /* flag: St. Pierre & Miquelon */
let 🇵🇳 = 1 /* flag: Pitcairn Islands */
let 🇵🇷 = 1 /* flag: Puerto Rico */
let 🇵🇸 = 1 /* flag: Palestinian Territories */
let 🇵🇹 = 1 /* flag: Portugal */
let 🇵🇼 = 1 /* flag: Palau */
let 🇵🇾 = 1 /* flag: Paraguay */
let 🇶🇦 = 1 /* flag: Qatar */
let 🇷🇪 = 1 /* flag: Réunion */
let 🇷🇴 = 1 /* flag: Romania */
let 🇷🇸 = 1 /* flag: Serbia */
let 🇷🇺 = 1 /* flag: Russia */
let 🇷🇼 = 1 /* flag: Rwanda */
let 🇸🇦 = 1 /* flag: Saudi Arabia */
let 🇸🇧 = 1 /* flag: Solomon Islands */
let 🇸🇨 = 1 /* flag: Seychelles */
let 🇸🇩 = 1 /* flag: Sudan */
let 🇸🇪 = 1 /* flag: Sweden */
let 🇸🇬 = 1 /* flag: Singapore */
let 🇸🇭 = 1 /* flag: St. Helena */
let 🇸🇮 = 1 /* flag: Slovenia */
let 🇸🇯 = 1 /* flag: Svalbard & Jan Mayen */
let 🇸🇰 = 1 /* flag: Slovakia */
let 🇸🇱 = 1 /* flag: Sierra Leone */
let 🇸🇲 = 1 /* flag: San Marino */
let 🇸🇳 = 1 /* flag: Senegal */
let 🇸🇴 = 1 /* flag: Somalia */
let 🇸🇷 = 1 /* flag: Suriname */
let 🇸🇸 = 1 /* flag: South Sudan */
let 🇸🇹 = 1 /* flag: São Tomé & Príncipe */
let 🇸🇻 = 1 /* flag: El Salvador */
let 🇸🇽 = 1 /* flag: Sint Maarten */
let 🇸🇾 = 1 /* flag: Syria */
let 🇸🇿 = 1 /* flag: Eswatini */
let 🇹🇦 = 1 /* flag: Tristan da Cunha */
let 🇹🇨 = 1 /* flag: Turks & Caicos Islands */
let 🇹🇩 = 1 /* flag: Chad */
let 🇹🇫 = 1 /* flag: French Southern Territories */
let 🇹🇬 = 1 /* flag: Togo */
let 🇹🇭 = 1 /* flag: Thailand */
let 🇹🇯 = 1 /* flag: Tajikistan */
let 🇹🇰 = 1 /* flag: Tokelau */
let 🇹🇱 = 1 /* flag: Timor-Leste */
let 🇹🇲 = 1 /* flag: Turkmenistan */
let 🇹🇳 = 1 /* flag: Tunisia */
let 🇹🇴 = 1 /* flag: Tonga */
let 🇹🇷 = 1 /* flag: Türkiye */
let 🇹🇹 = 1 /* flag: Trinidad & Tobago */
let 🇹🇻 = 1 /* flag: Tuvalu */
let 🇹🇼 = 1 /* flag: Taiwan */
let 🇹🇿 = 1 /* flag: Tanzania */
let 🇺🇦 = 1 /* flag: Ukraine */
let 🇺🇬 = 1 /* flag: Uganda */
let 🇺🇲 = 1 /* flag: U.S. Outlying Islands */
let 🇺🇳 = 1 /* flag: United Nations */
let 🇺🇸 = 1 /* flag: United States */
let 🇺🇾 = 1 /* flag: Uruguay */
let 🇺🇿 = 1 /* flag: Uzbekistan */
let 🇻🇦 = 1 /* flag: Vatican City */
let 🇻🇨 = 1 /* flag: St. Vincent & Grenadines */
let 🇻🇪 = 1 /* flag: Venezuela */
let 🇻🇬 = 1 /* flag: British Virgin Islands */
let 🇻🇮 = 1 /* flag: U.S. Virgin Islands */
let 🇻🇳 = 1 /* flag: Vietnam */
let 🇻🇺 = 1 /* flag: Vanuatu */
let 🇼🇫 = 1 /* flag: Wallis & Futuna */
let 🇼🇸 = 1 /* flag: Samoa */
let 🇽🇰 = 1 /* flag: Kosovo */
let 🇾🇪 = 1 /* flag: Yemen */
let 🇾🇹 = 1 /* flag: Mayotte */
let 🇿🇦 = 1 /* flag: South Africa */
let 🇿🇲 = 1 /* flag: Zambia */
let 🇿🇼 = 1 /* flag: Zimbabwe */
let 🏴󠁧󠁢󠁥󠁮󠁧󠁿 = 1 /* flag: England */
let 🏴󠁧󠁢󠁳󠁣󠁴󠁿 = 1 /* flag: Scotland */
let 🏴󠁧󠁢󠁷󠁬󠁳󠁿 = 1 /* flag: Wales */
