let ☺️ = 1 /* smiling face */
let 🙂‍↔️ = 1 /* head shaking horizontally */
let 🙂‍↕️ = 1 /* head shaking vertically */
let ☹️ = 1 /* frowning face */
let ☠️ = 1 /* skull and crossbones */
let ❣️ = 1 /* heart exclamation */
let ❤️‍🔥 = 1 /* heart on fire */
let ❤️‍🩹 = 1 /* mending heart */
let ❤️ = 1 /* red heart */
let ✋️ = 1 /* raised hand */
let ✌️ = 1 /* victory hand */
let ☝️ = 1 /* index pointing up */
let ✊️ = 1 /* raised fist */
let ✍️ = 1 /* writing hand */
let 🧔‍♂️ = 1 /* man: beard */
let 🧔‍♀️ = 1 /* woman: beard */
let 👱‍♀️ = 1 /* woman: blond hair */
let 👱‍♂️ = 1 /* man: blond hair */
let 🙍‍♂️ = 1 /* man frowning */
let 🙍‍♀️ = 1 /* woman frowning */
let 🙎‍♂️ = 1 /* man pouting */
let 🙎‍♀️ = 1 /* woman pouting */
let 🙅‍♂️ = 1 /* man gesturing NO */
let 🙅‍♀️ = 1 /* woman gesturing NO */
let 🙆‍♂️ = 1 /* man gesturing OK */
let 🙆‍♀️ = 1 /* woman gesturing OK */
let 💁‍♂️ = 1 /* man tipping hand */
let 💁‍♀️ = 1 /* woman tipping hand */
let 🙋‍♂️ = 1 /* man raising hand */
let 🙋‍♀️ = 1 /* woman raising hand */
let 🧏‍♂️ = 1 /* deaf man */
let 🧏‍♀️ = 1 /* deaf woman */
let 🙇‍♂️ = 1 /* man bowing */
let 🙇‍♀️ = 1 /* woman bowing */
let 🤦‍♂️ = 1 /* man facepalming */
let 🤦‍♀️ = 1 /* woman facepalming */
let 🤷‍♂️ = 1 /* man shrugging */
let 🤷‍♀️ = 1 /* woman shrugging */
let 🧑‍⚕️ = 1 /* health worker */
let 👨‍⚕️ = 1 /* man health worker */
let 👩‍⚕️ = 1 /* woman health worker */
let 🧑‍⚖️ = 1 /* judge */
let 👨‍⚖️ = 1 /* man judge */
let 👩‍⚖️ = 1 /* woman judge */
let 🧑‍✈️ = 1 /* pilot */
let 👨‍✈️ = 1 /* man pilot */
let 👩‍✈️ = 1 /* woman pilot */
let 👮‍♂️ = 1 /* man police officer */
let 👮‍♀️ = 1 /* woman police officer */
let 🕵️‍♂️ = 1 /* man detective */
let 🕵️‍♀️ = 1 /* woman detective */
let 💂‍♂️ = 1 /* man guard */
let 💂‍♀️ = 1 /* woman guard */
let 👷‍♂️ = 1 /* man construction worker */
let 👷‍♀️ = 1 /* woman construction worker */
let 👳‍♂️ = 1 /* man wearing turban */
let 👳‍♀️ = 1 /* woman wearing turban */
let 🤵‍♂️ = 1 /* man in tuxedo */
let 🤵‍♀️ = 1 /* woman in tuxedo */
let 👰‍♂️ = 1 /* man with veil */
let 👰‍♀️ = 1 /* woman with veil */
let 🦸‍♂️ = 1 /* man superhero */
let 🦸‍♀️ = 1 /* woman superhero */
let 🦹‍♂️ = 1 /* man supervillain */
let 🦹‍♀️ = 1 /* woman supervillain */
let 🧙‍♂️ = 1 /* man mage */
let 🧙‍♀️ = 1 /* woman mage */
let 🧚‍♂️ = 1 /* man fairy */
let 🧚‍♀️ = 1 /* woman fairy */
let 🧛‍♂️ = 1 /* man vampire */
let 🧛‍♀️ = 1 /* woman vampire */
let 🧜‍♂️ = 1 /* merman */
let 🧜‍♀️ = 1 /* mermaid */
let 🧝‍♂️ = 1 /* man elf */
let 🧝‍♀️ = 1 /* woman elf */
let 🧞‍♂️ = 1 /* man genie */
let 🧞‍♀️ = 1 /* woman genie */
let 🧟‍♂️ = 1 /* man zombie */
let 🧟‍♀️ = 1 /* woman zombie */
let 💆‍♂️ = 1 /* man getting massage */
let 💆‍♀️ = 1 /* woman getting massage */
let 💇‍♂️ = 1 /* man getting haircut */
let 💇‍♀️ = 1 /* woman getting haircut */
let 🚶‍♂️ = 1 /* man walking */
let 🚶‍♀️ = 1 /* woman walking */
let 🚶‍➡️ = 1 /* person walking facing right */
let 🚶‍♀️‍➡️ = 1 /* woman walking facing right */
let 🚶‍♂️‍➡️ = 1 /* man walking facing right */
let 🧍‍♂️ = 1 /* man standing */
let 🧍‍♀️ = 1 /* woman standing */
let 🧎‍♂️ = 1 /* man kneeling */
let 🧎‍♀️ = 1 /* woman kneeling */
let 🧎‍➡️ = 1 /* person kneeling facing right */
let 🧎‍♀️‍➡️ = 1 /* woman kneeling facing right */
let 🧎‍♂️‍➡️ = 1 /* man kneeling facing right */
let 🧑‍🦯‍➡️ = 1 /* person with white cane facing right */
let 👨‍🦯‍➡️ = 1 /* man with white cane facing right */
let 👩‍🦯‍➡️ = 1 /* woman with white cane facing right */
let 🧑‍🦼‍➡️ = 1 /* person in motorized wheelchair facing right */
let 👨‍🦼‍➡️ = 1 /* man in motorized wheelchair facing right */
let 👩‍🦼‍➡️ = 1 /* woman in motorized wheelchair facing right */
let 🧑‍🦽‍➡️ = 1 /* person in manual wheelchair facing right */
let 👨‍🦽‍➡️ = 1 /* man in manual wheelchair facing right */
let 👩‍🦽‍➡️ = 1 /* woman in manual wheelchair facing right */
let 🏃‍♂️ = 1 /* man running */
let 🏃‍♀️ = 1 /* woman running */
let 🏃‍➡️ = 1 /* person running facing right */
let 🏃‍♀️‍➡️ = 1 /* woman running facing right */
let 🏃‍♂️‍➡️ = 1 /* man running facing right */
let 👯‍♂️ = 1 /* men with bunny ears */
let 👯‍♀️ = 1 /* women with bunny ears */
let 🧖‍♂️ = 1 /* man in steamy room */
let 🧖‍♀️ = 1 /* woman in steamy room */
let 🧗‍♂️ = 1 /* man climbing */
let 🧗‍♀️ = 1 /* woman climbing */
let ⛷️ = 1 /* skier */
let 🏌️‍♂️ = 1 /* man golfing */
let 🏌️‍♀️ = 1 /* woman golfing */
let 🏄‍♂️ = 1 /* man surfing */
let 🏄‍♀️ = 1 /* woman surfing */
let 🚣‍♂️ = 1 /* man rowing boat */
let 🚣‍♀️ = 1 /* woman rowing boat */
let 🏊‍♂️ = 1 /* man swimming */
let 🏊‍♀️ = 1 /* woman swimming */
let ⛹️ = 1 /* person bouncing ball */
let ⛹️‍♂️ = 1 /* man bouncing ball */
let ⛹️‍♀️ = 1 /* woman bouncing ball */
let 🏋️‍♂️ = 1 /* man lifting weights */
let 🏋️‍♀️ = 1 /* woman lifting weights */
let 🚴‍♂️ = 1 /* man biking */
let 🚴‍♀️ = 1 /* woman biking */
let 🚵‍♂️ = 1 /* man mountain biking */
let 🚵‍♀️ = 1 /* woman mountain biking */
let 🤸‍♂️ = 1 /* man cartwheeling */
let 🤸‍♀️ = 1 /* woman cartwheeling */
let 🤼‍♂️ = 1 /* men wrestling */
let 🤼‍♀️ = 1 /* women wrestling */
let 🤽‍♂️ = 1 /* man playing water polo */
let 🤽‍♀️ = 1 /* woman playing water polo */
let 🤾‍♂️ = 1 /* man playing handball */
let 🤾‍♀️ = 1 /* woman playing handball */
let 🤹‍♂️ = 1 /* man juggling */
let 🤹‍♀️ = 1 /* woman juggling */
let 🧘‍♂️ = 1 /* man in lotus position */
let 🧘‍♀️ = 1 /* woman in lotus position */
let 👩‍❤️‍💋‍👨 = 1 /* kiss: woman, man */
let 👨‍❤️‍💋‍👨 = 1 /* kiss: man, man */
let 👩‍❤️‍💋‍👩 = 1 /* kiss: woman, woman */
let 👩‍❤️‍👨 = 1 /* couple with heart: woman, man */
let 👨‍❤️‍👨 = 1 /* couple with heart: man, man */
let 👩‍❤️‍👩 = 1 /* couple with heart: woman, woman */
let 🐈‍⬛ = 1 /* black cat */
let 🐻‍❄️ = 1 /* polar bear */
let 🐦‍⬛ = 1 /* black bird */
let ☘️ = 1 /* shamrock */
let ☕️ = 1 /* hot beverage */
let ⛰️ = 1 /* mountain */
let ⛪️ = 1 /* church */
let ⛩️ = 1 /* shinto shrine */
let ⛲️ = 1 /* fountain */
let ⛺️ = 1 /* tent */
let ♨️ = 1 /* hot springs */
let ⛽️ = 1 /* fuel pump */
let ⚓️ = 1 /* anchor */
let ⛵️ = 1 /* sailboat */
let ⛴️ = 1 /* ferry */
let ✈️ = 1 /* airplane */
let ⌛️ = 1 /* hourglass done */
let ⏳️ = 1 /* hourglass not done */
let ⌚️ = 1 /* watch */
let ⏰️ = 1 /* alarm clock */
let ⏱️ = 1 /* stopwatch */
let ⏲️ = 1 /* timer clock */
let ☀️ = 1 /* sun */
let ⭐️ = 1 /* star */
let ☁️ = 1 /* cloud */
let ⛅️ = 1 /* sun behind cloud */
let ⛈️ = 1 /* cloud with lightning and rain */
let ☂️ = 1 /* umbrella */
let ☔️ = 1 /* umbrella with rain drops */
let ⛱️ = 1 /* umbrella on ground */
let ⚡️ = 1 /* high voltage */
let ❄️ = 1 /* snowflake */
let ☃️ = 1 /* snowman */
let ⛄️ = 1 /* snowman without snow */
let ☄️ = 1 /* comet */
let ✨️ = 1 /* sparkles */
let ⚽️ = 1 /* soccer ball */
let ⚾️ = 1 /* baseball */
let ⛳️ = 1 /* flag in hole */
let ⛸️ = 1 /* ice skate */
let ♠️ = 1 /* spade suit */
let ♥️ = 1 /* heart suit */
let ♦️ = 1 /* diamond suit */
let ♣️ = 1 /* club suit */
let ♟️ = 1 /* chess pawn */
let ⛑️ = 1 /* rescue worker’s helmet */
let ☎️ = 1 /* telephone */
let ⌨️ = 1 /* keyboard */
let ✉️ = 1 /* envelope */
let ✏️ = 1 /* pencil */
let ✒️ = 1 /* black nib */
let ✂️ = 1 /* scissors */
let ⛏️ = 1 /* pick */
let ⚒️ = 1 /* hammer and pick */
let ⚔️ = 1 /* crossed swords */
let ⚙️ = 1 /* gear */
let ⚖️ = 1 /* balance scale */
let ⛓️‍💥 = 1 /* broken chain */
let ⛓️ = 1 /* chains */
let ⚗️ = 1 /* alembic */
let ⚰️ = 1 /* coffin */
let ⚱️ = 1 /* funeral urn */
let ♿️ = 1 /* wheelchair symbol */
let ⚠️ = 1 /* warning */
let ⛔️ = 1 /* no entry */
let ☢️ = 1 /* radioactive */
let ☣️ = 1 /* biohazard */
let ⬆️ = 1 /* up arrow */
let ↗️ = 1 /* up-right arrow */
let ➡️ = 1 /* right arrow */
let ↘️ = 1 /* down-right arrow */
let ⬇️ = 1 /* down arrow */
let ↙️ = 1 /* down-left arrow */
let ⬅️ = 1 /* left arrow */
let ↖️ = 1 /* up-left arrow */
let ↕️ = 1 /* up-down arrow */
let ↔️ = 1 /* left-right arrow */
let ↩️ = 1 /* right arrow curving left */
let ↪️ = 1 /* left arrow curving right */
let ⤴️ = 1 /* right arrow curving up */
let ⤵️ = 1 /* right arrow curving down */
let ⚛️ = 1 /* atom symbol */
let ✡️ = 1 /* star of David */
let ☸️ = 1 /* wheel of dharma */
let ☯️ = 1 /* yin yang */
let ✝️ = 1 /* latin cross */
let ☦️ = 1 /* orthodox cross */
let ☪️ = 1 /* star and crescent */
let ☮️ = 1 /* peace symbol */
let ♈️ = 1 /* Aries */
let ♉️ = 1 /* Taurus */
let ♊️ = 1 /* Gemini */
let ♋️ = 1 /* Cancer */
let ♌️ = 1 /* Leo */
let ♍️ = 1 /* Virgo */
let ♎️ = 1 /* Libra */
let ♏️ = 1 /* Scorpio */
let ♐️ = 1 /* Sagittarius */
let ♑️ = 1 /* Capricorn */
let ♒️ = 1 /* Aquarius */
let ♓️ = 1 /* Pisces */
let ⛎️ = 1 /* Ophiuchus */
let ▶️ = 1 /* play button */
let ⏩️ = 1 /* fast-forward button */
let ⏭️ = 1 /* next track button */
let ⏯️ = 1 /* play or pause button */
let ◀️ = 1 /* reverse button */
let ⏪️ = 1 /* fast reverse button */
let ⏮️ = 1 /* last track button */
let ⏫️ = 1 /* fast up button */
let ⏬️ = 1 /* fast down button */
let ⏸️ = 1 /* pause button */
let ⏹️ = 1 /* stop button */
let ⏺️ = 1 /* record button */
let ⏏️ = 1 /* eject button */
let ♀️ = 1 /* female sign */
let ♂️ = 1 /* male sign */
let ⚧️ = 1 /* transgender symbol */
let ✖️ = 1 /* multiply */
let ➕️ = 1 /* plus */
let ➖️ = 1 /* minus */
let ➗️ = 1 /* divide */
let ♾️ = 1 /* infinity */
let ‼️ = 1 /* double exclamation mark */
let ⁉️ = 1 /* exclamation question mark */
let ❓️ = 1 /* red question mark */
let ❔️ = 1 /* white question mark */
let ❕️ = 1 /* white exclamation mark */
let ❗️ = 1 /* red exclamation mark */
let 〰️ = 1 /* wavy dash */
let ⚕️ = 1 /* medical symbol */
let ♻️ = 1 /* recycling symbol */
let ⚜️ = 1 /* fleur-de-lis */
let ⭕️ = 1 /* hollow red circle */
let ✅️ = 1 /* check mark button */
let ☑️ = 1 /* check box with check */
let ✔️ = 1 /* check mark */
let ❌️ = 1 /* cross mark */
let ❎️ = 1 /* cross mark button */
let ➰️ = 1 /* curly loop */
let ➿️ = 1 /* double curly loop */
let ✳️ = 1 /* eight-spoked asterisk */
let ✴️ = 1 /* eight-pointed star */
let ❇️ = 1 /* sparkle */
let ©️ = 1 /* copyright */
let ®️ = 1 /* registered */
let #️⃣ = 1 /* keycap: # */
let *️⃣ = 1 /* keycap: * */
let 0️⃣ = 1 /* keycap: 0 */
let 1️⃣ = 1 /* keycap: 1 */
let 2️⃣ = 1 /* keycap: 2 */
let 3️⃣ = 1 /* keycap: 3 */
let 4️⃣ = 1 /* keycap: 4 */
let 5️⃣ = 1 /* keycap: 5 */
let 6️⃣ = 1 /* keycap: 6 */
let 7️⃣ = 1 /* keycap: 7 */
let 8️⃣ = 1 /* keycap: 8 */
let 9️⃣ = 1 /* keycap: 9 */
let ⚫️ = 1 /* black circle */
let ⚪️ = 1 /* white circle */
let ⬛️ = 1 /* black large square */
let ⬜️ = 1 /* white large square */
let ◼️ = 1 /* black medium square */
let ◻️ = 1 /* white medium square */
let ◾️ = 1 /* black medium-small square */
let ◽️ = 1 /* white medium-small square */
let ▪️ = 1 /* black small square */
let ▫️ = 1 /* white small square */
let 🏳️‍⚧️ = 1 /* transgender flag */
let 🏴‍☠️ = 1 /* pirate flag */
